---
# Ansible Galaxy Collections
collections:
  - name: community.general
    version: ">=8.0.0"
  
  - name: ansible.posix
    version: ">=1.5.0"

# Python packages required (install via pip)
# pip install python-hpilo requests
